Reshuffle
Signed-off-by: Piotr Gorski <lucjan.lucjanov@gmail.com>

diff --git a/5.17/zstd-dev-patches/0001-zstd-dev-patches.patch b/5.17/zstd-dev-patches/0001-zstd-dev-patches.patch
--- a/5.17/zstd-dev-patches/0001-zstd-dev-patches.patch
+++ b/5.17/zstd-dev-patches/0001-zstd-dev-patches.patch
@@ -1,7 +1,7 @@
-From ad223807e78515965c0051fbb0092bdd8b6d8af7 Mon Sep 17 00:00:00 2001
+From dbcb694f402552f596fe83ebbf77261b25a16eb0 Mon Sep 17 00:00:00 2001
 From: Nick Terrell <terrelln@fb.com>
 Date: Mon, 15 Nov 2021 20:41:53 -0800
-Subject: [PATCH 1/2] lib: zstd: Remove large inline functions in zstd_lazy.c
+Subject: [PATCH 1/6] lib: zstd: Remove large inline functions in zstd_lazy.c
 
 Backport of upstream PR #2828 [0].
 
@@ -318,13 +318,13 @@ index fb54d4e28..1db22db5b 100644
      U32 offset_1 = rep[0], offset_2 = rep[1];
  
 -- 
-2.35.1.354.g715d08a9e5
+2.36.0.rc1
 
 
-From 510b213df9471a5d70e755d4d80a15290d89e8c3 Mon Sep 17 00:00:00 2001
+From 808d6311f8c7297986a5901cc8d106f86869c377 Mon Sep 17 00:00:00 2001
 From: Nick Terrell <terrelln@fb.com>
 Date: Mon, 15 Nov 2021 20:56:42 -0800
-Subject: [PATCH 2/2] lib: zstd: Remove large inline functions from
+Subject: [PATCH 2/6] lib: zstd: Remove large inline functions from
  zstd_{double_,}fast.c
 
 Backport of upstream PR #2863 [0].
@@ -598,5 +598,557 @@ index 96b7d48e2..e0652e31d 100644
      }
  }
 -- 
-2.35.1.354.g715d08a9e5
+2.36.0.rc1
+
+
+From 66af59adacbcd0aeb02c707463e12eefaaf1b076 Mon Sep 17 00:00:00 2001
+From: Takashi Iwai <tiwai@suse.de>
+Date: Wed, 27 Jan 2021 16:22:48 +0100
+Subject: [PATCH 3/6] firmware: Add the support for ZSTD-compressed firmware
+ files
+
+Due to the popular demands on ZSTD, here is a patch to add a support
+of ZSTD-compressed firmware files via the direct firmware loader.
+It's just like XZ-compressed file support, providing a decompressor
+with ZSTD.  Since ZSTD API can give the decompression size beforehand,
+the code is even simpler than XZ.
+
+Link: https://lore.kernel.org/all/20210127154939.13288-1-tiwai@suse.de/
+Signed-off-by: Takashi Iwai <tiwai@suse.de>
+---
+ drivers/base/firmware_loader/Kconfig | 22 +++++++--
+ drivers/base/firmware_loader/main.c  | 74 ++++++++++++++++++++++++++--
+ 2 files changed, 88 insertions(+), 8 deletions(-)
+
+diff --git a/drivers/base/firmware_loader/Kconfig b/drivers/base/firmware_loader/Kconfig
+index 5b24f3959..581bfe2c9 100644
+--- a/drivers/base/firmware_loader/Kconfig
++++ b/drivers/base/firmware_loader/Kconfig
+@@ -157,17 +157,29 @@ config FW_LOADER_USER_HELPER_FALLBACK
+ 
+ config FW_LOADER_COMPRESS
+ 	bool "Enable compressed firmware support"
+-	select FW_LOADER_PAGED_BUF
+-	select XZ_DEC
+ 	help
+ 	  This option enables the support for loading compressed firmware
+ 	  files. The caller of firmware API receives the decompressed file
+ 	  content. The compressed file is loaded as a fallback, only after
+ 	  loading the raw file failed at first.
+ 
+-	  Currently only XZ-compressed files are supported, and they have to
+-	  be compressed with either none or crc32 integrity check type (pass
+-	  "-C crc32" option to xz command).
++if FW_LOADER_COMPRESS
++config FW_LOADER_COMPRESS_XZ
++	bool "Enable XZ-compressed firmware support"
++	select FW_LOADER_PAGED_BUF
++	select XZ_DEC
++	help
++	  This option adds the support for XZ-compressed files.
++	  The files have to be compressed with either none or crc32
++	  integrity check type (pass "-C crc32" option to xz command).
++
++config FW_LOADER_COMPRESS_ZSTD
++	bool "Enable ZSTD-compressed firmware support"
++	select ZSTD_DECOMPRESS
++	help
++	  This option adds the support for ZSTD-compressed files.
++
++endif # FW_LOADER_COMPRESS
+ 
+ config FW_CACHE
+ 	bool "Enable firmware caching during suspend"
+diff --git a/drivers/base/firmware_loader/main.c b/drivers/base/firmware_loader/main.c
+index 94d1789a2..6e94f7e8c 100644
+--- a/drivers/base/firmware_loader/main.c
++++ b/drivers/base/firmware_loader/main.c
+@@ -35,6 +35,7 @@
+ #include <linux/syscore_ops.h>
+ #include <linux/reboot.h>
+ #include <linux/security.h>
++#include <linux/zstd.h>
+ #include <linux/xz.h>
+ 
+ #include <generated/utsrelease.h>
+@@ -304,10 +305,72 @@ int fw_map_paged_buf(struct fw_priv *fw_priv)
+ }
+ #endif
+ 
++/*
++ * ZSTD-compressed firmware support
++ */
++#ifdef CONFIG_FW_LOADER_COMPRESS_ZSTD
++static int fw_decompress_zstd(struct device *dev, struct fw_priv *fw_priv,
++			      size_t in_size, const void *in_buffer)
++{
++	size_t len, out_size, workspace_size;
++	void *workspace, *out_buf;
++	zstd_dctx *ctx;
++	int err;
++
++	if (fw_priv->data) {
++		out_size = fw_priv->allocated_size;
++		out_buf = fw_priv->data;
++	} else {
++		out_size = zstd_find_frame_compressed_size(in_buffer, in_size);
++		if (out_size == ZSTD_CONTENTSIZE_UNKNOWN ||
++		    out_size == ZSTD_CONTENTSIZE_ERROR) {
++			dev_dbg(dev, "%s: invalid decompression size\n", __func__);
++			return -EINVAL;
++		}
++		out_buf = vzalloc(out_size);
++		if (!out_buf)
++			return -ENOMEM;
++	}
++
++	workspace_size = zstd_dctx_workspace_bound();
++	workspace = kvzalloc(workspace_size, GFP_KERNEL);
++	if (!workspace) {
++		err = -ENOMEM;
++		goto error;
++	}
++
++	ctx = zstd_init_dctx(workspace, workspace_size);
++	if (!ctx) {
++		dev_dbg(dev, "%s: failed to initialize context\n", __func__);
++		err = -EINVAL;
++		goto error;
++	}
++
++	len = zstd_decompress_dctx(ctx, out_buf, out_size, in_buffer, in_size);
++	if (zstd_is_error(len)) {
++		dev_dbg(dev, "%s: failed to decompress: %d\n", __func__,
++			zstd_get_error_code(len));
++		err = -EINVAL;
++		goto error;
++	}
++
++	fw_priv->size = len;
++	if (!fw_priv->data)
++		fw_priv->data = out_buf;
++	err = 0;
++
++ error:
++	kvfree(workspace);
++	if (!fw_priv->data)
++		vfree(out_buf);
++	return err;
++}
++#endif /* CONFIG_FW_LOADER_COMPRESS_ZSTD */
++
+ /*
+  * XZ-compressed firmware support
+  */
+-#ifdef CONFIG_FW_LOADER_COMPRESS
++#ifdef CONFIG_FW_LOADER_COMPRESS_XZ
+ /* show an error and return the standard error code */
+ static int fw_decompress_xz_error(struct device *dev, enum xz_ret xz_ret)
+ {
+@@ -401,7 +464,7 @@ static int fw_decompress_xz(struct device *dev, struct fw_priv *fw_priv,
+ 	else
+ 		return fw_decompress_xz_pages(dev, fw_priv, in_size, in_buffer);
+ }
+-#endif /* CONFIG_FW_LOADER_COMPRESS */
++#endif /* CONFIG_FW_LOADER_COMPRESS_XZ */
+ 
+ /* direct firmware loading support */
+ static char fw_path_para[256];
+@@ -757,7 +820,12 @@ _request_firmware(const struct firmware **firmware_p, const char *name,
+ 	if (!(opt_flags & FW_OPT_PARTIAL))
+ 		nondirect = true;
+ 
+-#ifdef CONFIG_FW_LOADER_COMPRESS
++#ifdef CONFIG_FW_LOADER_COMPRESS_ZSTD
++	if (ret == -ENOENT && nondirect)
++		ret = fw_get_filesystem_firmware(device, fw->priv, ".zst",
++						 fw_decompress_zstd);
++#endif
++#ifdef CONFIG_FW_LOADER_COMPRESS_XZ
+ 	if (ret == -ENOENT && nondirect)
+ 		ret = fw_get_filesystem_firmware(device, fw->priv, ".xz",
+ 						 fw_decompress_xz);
+-- 
+2.36.0.rc1
+
+
+From 0bddf60c0af008cfc83a502edb3efd20a4077af0 Mon Sep 17 00:00:00 2001
+From: Takashi Iwai <tiwai@suse.de>
+Date: Wed, 27 Jan 2021 16:32:55 +0100
+Subject: [PATCH 4/6] selftests: firmware: Simplify test patterns
+
+The test patterns are almost same in three sequential tests.
+Make the unified helper function for improving the readability.
+
+Link: https://lore.kernel.org/all/20210127154939.13288-1-tiwai@suse.de/
+Signed-off-by: Takashi Iwai <tiwai@suse.de>
+---
+ .../selftests/firmware/fw_filesystem.sh       | 106 +++++-------------
+ 1 file changed, 30 insertions(+), 76 deletions(-)
+
+diff --git a/tools/testing/selftests/firmware/fw_filesystem.sh b/tools/testing/selftests/firmware/fw_filesystem.sh
+index c2a2a1001..2424a97da 100755
+--- a/tools/testing/selftests/firmware/fw_filesystem.sh
++++ b/tools/testing/selftests/firmware/fw_filesystem.sh
+@@ -435,6 +435,32 @@ test_request_partial_firmware_into_buf()
+ 	echo "OK"
+ }
+ 
++do_tests ()
++{
++	mode="$1"
++	suffix="$2"
++
++	for i in $(seq 1 5); do
++		test_batched_request_firmware$suffix $i $mode
++	done
++
++	for i in $(seq 1 5); do
++		test_batched_request_firmware_into_buf$suffix $i $mode
++	done
++
++	for i in $(seq 1 5); do
++		test_batched_request_firmware_direct$suffix $i $mode
++	done
++
++	for i in $(seq 1 5); do
++		test_request_firmware_nowait_uevent$suffix $i $mode
++	done
++
++	for i in $(seq 1 5); do
++		test_request_firmware_nowait_custom$suffix $i $mode
++	done
++}
++
+ # Only continue if batched request triggers are present on the
+ # test-firmware driver
+ test_config_present
+@@ -442,25 +468,7 @@ test_config_present
+ # test with the file present
+ echo
+ echo "Testing with the file present..."
+-for i in $(seq 1 5); do
+-	test_batched_request_firmware $i normal
+-done
+-
+-for i in $(seq 1 5); do
+-	test_batched_request_firmware_into_buf $i normal
+-done
+-
+-for i in $(seq 1 5); do
+-	test_batched_request_firmware_direct $i normal
+-done
+-
+-for i in $(seq 1 5); do
+-	test_request_firmware_nowait_uevent $i normal
+-done
+-
+-for i in $(seq 1 5); do
+-	test_request_firmware_nowait_custom $i normal
+-done
++do_tests normal
+ 
+ # Partial loads cannot use fallback, so do not repeat tests.
+ test_request_partial_firmware_into_buf 0 10
+@@ -472,25 +480,7 @@ test_request_partial_firmware_into_buf 2 10
+ # a hung task, which would require a hard reset.
+ echo
+ echo "Testing with the file missing..."
+-for i in $(seq 1 5); do
+-	test_batched_request_firmware_nofile $i
+-done
+-
+-for i in $(seq 1 5); do
+-	test_batched_request_firmware_into_buf_nofile $i
+-done
+-
+-for i in $(seq 1 5); do
+-	test_batched_request_firmware_direct_nofile $i
+-done
+-
+-for i in $(seq 1 5); do
+-	test_request_firmware_nowait_uevent_nofile $i
+-done
+-
+-for i in $(seq 1 5); do
+-	test_request_firmware_nowait_custom_nofile $i
+-done
++do_tests nofile _nofile
+ 
+ # Partial loads cannot use fallback, so do not repeat tests.
+ test_request_partial_firmware_into_buf_nofile 0 10
+@@ -505,48 +495,12 @@ xz -9 -C crc32 -k $FW
+ config_set_name $NAME
+ echo
+ echo "Testing with both plain and xz files present..."
+-for i in $(seq 1 5); do
+-	test_batched_request_firmware $i both
+-done
+-
+-for i in $(seq 1 5); do
+-	test_batched_request_firmware_into_buf $i both
+-done
+-
+-for i in $(seq 1 5); do
+-	test_batched_request_firmware_direct $i both
+-done
+-
+-for i in $(seq 1 5); do
+-	test_request_firmware_nowait_uevent $i both
+-done
+-
+-for i in $(seq 1 5); do
+-	test_request_firmware_nowait_custom $i both
+-done
++do_tests both
+ 
+ # test with only xz file present
+ mv "$FW" "${FW}-orig"
+ echo
+ echo "Testing with only xz file present..."
+-for i in $(seq 1 5); do
+-	test_batched_request_firmware $i xzonly
+-done
+-
+-for i in $(seq 1 5); do
+-	test_batched_request_firmware_into_buf $i xzonly
+-done
+-
+-for i in $(seq 1 5); do
+-	test_batched_request_firmware_direct $i xzonly
+-done
+-
+-for i in $(seq 1 5); do
+-	test_request_firmware_nowait_uevent $i xzonly
+-done
+-
+-for i in $(seq 1 5); do
+-	test_request_firmware_nowait_custom $i xzonly
+-done
++do_tests xzonly
+ 
+ exit 0
+-- 
+2.36.0.rc1
+
+
+From 30e2fc8201744bef6469ac2ca6eb2eb9a63f5de9 Mon Sep 17 00:00:00 2001
+From: Takashi Iwai <tiwai@suse.de>
+Date: Wed, 27 Jan 2021 16:34:53 +0100
+Subject: [PATCH 5/6] selftest: firmware: Fix the request_firmware_into_buf()
+ test for XZ format
+
+The test uses a different firmware name, and we forgot to adapt for
+the XZ compressed file tests.
+
+https://lore.kernel.org/all/20210127154939.13288-1-tiwai@suse.de/
+Signed-off-by: Takashi Iwai <tiwai@suse.de>
+---
+ drivers/base/firmware_loader/main.c               | 10 ++++++----
+ tools/testing/selftests/firmware/fw_filesystem.sh |  2 ++
+ 2 files changed, 8 insertions(+), 4 deletions(-)
+
+diff --git a/drivers/base/firmware_loader/main.c b/drivers/base/firmware_loader/main.c
+index 6e94f7e8c..771387976 100644
+--- a/drivers/base/firmware_loader/main.c
++++ b/drivers/base/firmware_loader/main.c
+@@ -321,12 +321,14 @@ static int fw_decompress_zstd(struct device *dev, struct fw_priv *fw_priv,
+ 		out_size = fw_priv->allocated_size;
+ 		out_buf = fw_priv->data;
+ 	} else {
+-		out_size = zstd_find_frame_compressed_size(in_buffer, in_size);
+-		if (out_size == ZSTD_CONTENTSIZE_UNKNOWN ||
+-		    out_size == ZSTD_CONTENTSIZE_ERROR) {
+-			dev_dbg(dev, "%s: invalid decompression size\n", __func__);
++		zstd_frame_header params;
++
++		if (zstd_get_frame_header(&params, in_buffer, in_size) ||
++		    params.frameContentSize == ZSTD_CONTENTSIZE_UNKNOWN) {
++			dev_dbg(dev, "%s: invalid zstd header\n", __func__);
+ 			return -EINVAL;
+ 		}
++		out_size = params.frameContentSize;
+ 		out_buf = vzalloc(out_size);
+ 		if (!out_buf)
+ 			return -ENOMEM;
+diff --git a/tools/testing/selftests/firmware/fw_filesystem.sh b/tools/testing/selftests/firmware/fw_filesystem.sh
+index 2424a97da..f1976e650 100755
+--- a/tools/testing/selftests/firmware/fw_filesystem.sh
++++ b/tools/testing/selftests/firmware/fw_filesystem.sh
+@@ -492,6 +492,7 @@ test "$HAS_FW_LOADER_COMPRESS" != "yes" && exit 0
+ 
+ # test with both files present
+ xz -9 -C crc32 -k $FW
++xz -9 -C crc32 -k $FW_INTO_BUF
+ config_set_name $NAME
+ echo
+ echo "Testing with both plain and xz files present..."
+@@ -499,6 +500,7 @@ do_tests both
+ 
+ # test with only xz file present
+ mv "$FW" "${FW}-orig"
++mv "$FW_INTO_BUF" "${FW_INTO_BUF}-orig"
+ echo
+ echo "Testing with only xz file present..."
+ do_tests xzonly
+-- 
+2.36.0.rc1
+
+
+From 1b100b387f37c56b68e247e6c7d024664470fea5 Mon Sep 17 00:00:00 2001
+From: Takashi Iwai <tiwai () suse ! de>
+Date: Wed, 27 Jan 2021 15:49:39 +0000
+Subject: [PATCH 6/6] selftest: firmware: Add ZSTD compressed file tests
+
+It's similar like XZ compressed files.  For the simplicity, both XZ
+and ZSTD tests are done in a single function.  The format is specified
+via $COMPRESS_FORMAT and the compression function is pre-defined.
+
+Signed-off-by: Takashi Iwai <tiwai@suse.de>
+---
+ .../selftests/firmware/fw_filesystem.sh       | 75 ++++++++++++++-----
+ tools/testing/selftests/firmware/fw_lib.sh    | 12 ++-
+ 2 files changed, 64 insertions(+), 23 deletions(-)
+
+diff --git a/tools/testing/selftests/firmware/fw_filesystem.sh b/tools/testing/selftests/firmware/fw_filesystem.sh
+index f1976e650..abaceac83 100755
+--- a/tools/testing/selftests/firmware/fw_filesystem.sh
++++ b/tools/testing/selftests/firmware/fw_filesystem.sh
+@@ -211,7 +211,7 @@ read_firmwares()
+ 	else
+ 		fwfile="$FW"
+ 	fi
+-	if [ "$1" = "xzonly" ]; then
++	if [ "$1" = "componly" ]; then
+ 		fwfile="${fwfile}-orig"
+ 	fi
+ 	for i in $(seq 0 3); do
+@@ -235,7 +235,7 @@ read_partial_firmwares()
+ 		fwfile="${FW}"
+ 	fi
+ 
+-	if [ "$1" = "xzonly" ]; then
++	if [ "$1" = "componly" ]; then
+ 		fwfile="${fwfile}-orig"
+ 	fi
+ 
+@@ -409,10 +409,8 @@ test_request_firmware_nowait_custom()
+ 	config_unset_uevent
+ 	RANDOM_FILE_PATH=$(setup_random_file)
+ 	RANDOM_FILE="$(basename $RANDOM_FILE_PATH)"
+-	if [ "$2" = "both" ]; then
+-		xz -9 -C crc32 -k $RANDOM_FILE_PATH
+-	elif [ "$2" = "xzonly" ]; then
+-		xz -9 -C crc32 $RANDOM_FILE_PATH
++	if [ -n "$2" -a "$2" != "normal" ]; then
++		compress-"$2"-$COMPRESS_FORMAT $RANDOM_FILE_PATH
+ 	fi
+ 	config_set_name $RANDOM_FILE
+ 	config_trigger_async
+@@ -488,21 +486,58 @@ test_request_partial_firmware_into_buf_nofile 0 5
+ test_request_partial_firmware_into_buf_nofile 1 6
+ test_request_partial_firmware_into_buf_nofile 2 10
+ 
+-test "$HAS_FW_LOADER_COMPRESS" != "yes" && exit 0
++test_request_firmware_compressed ()
++{
++	export COMPRESS_FORMAT="$1"
+ 
+-# test with both files present
+-xz -9 -C crc32 -k $FW
+-xz -9 -C crc32 -k $FW_INTO_BUF
+-config_set_name $NAME
+-echo
+-echo "Testing with both plain and xz files present..."
+-do_tests both
++	# test with both files present
++	compress-both-$COMPRESS_FORMAT $FW
++	compress-both-$COMPRESS_FORMAT $FW_INTO_BUF
+ 
+-# test with only xz file present
+-mv "$FW" "${FW}-orig"
+-mv "$FW_INTO_BUF" "${FW_INTO_BUF}-orig"
+-echo
+-echo "Testing with only xz file present..."
+-do_tests xzonly
++	config_set_name $NAME
++	echo
++	echo "Testing with both plain and $COMPRESS_FORMAT files present..."
++	do_tests both
++
++	# test with only compressed file present
++	mv "$FW" "${FW}-orig"
++	mv "$FW_INTO_BUF" "${FW_INTO_BUF}-orig"
++
++	config_set_name $NAME
++	echo
++	echo "Testing with only $COMPRESS_FORMAT file present..."
++	do_tests componly
++
++	mv "${FW}-orig" "$FW"
++	mv "${FW_INTO_BUF}-orig" "$FW_INTO_BUF"
++}
++
++compress-both-XZ ()
++{
++	xz -k -9 -C crc32 "$@"
++}
++
++compress-componly-XZ ()
++{
++	xz -9 -C crc32 "$@"
++}
++
++compress-both-ZSTD ()
++{
++	zstd -q -k "$@"
++}
++
++compress-componly-ZSTD ()
++{
++	zstd -q --rm "$@"
++}
++
++if test "$HAS_FW_LOADER_COMPRESS_XZ" = "yes"; then
++	test_request_firmware_compressed XZ
++fi
++
++if test "$HAS_FW_LOADER_COMPRESS_ZSTD" = "yes"; then
++	test_request_firmware_compressed ZSTD
++fi
+ 
+ exit 0
+diff --git a/tools/testing/selftests/firmware/fw_lib.sh b/tools/testing/selftests/firmware/fw_lib.sh
+index 5b8c0fede..3fa8282b0 100755
+--- a/tools/testing/selftests/firmware/fw_lib.sh
++++ b/tools/testing/selftests/firmware/fw_lib.sh
+@@ -62,7 +62,8 @@ check_setup()
+ {
+ 	HAS_FW_LOADER_USER_HELPER="$(kconfig_has CONFIG_FW_LOADER_USER_HELPER=y)"
+ 	HAS_FW_LOADER_USER_HELPER_FALLBACK="$(kconfig_has CONFIG_FW_LOADER_USER_HELPER_FALLBACK=y)"
+-	HAS_FW_LOADER_COMPRESS="$(kconfig_has CONFIG_FW_LOADER_COMPRESS=y)"
++	HAS_FW_LOADER_COMPRESS_XZ="$(kconfig_has CONFIG_FW_LOADER_COMPRESS_XZ=y)"
++	HAS_FW_LOADER_COMPRESS_ZSTD="$(kconfig_has CONFIG_FW_LOADER_COMPRESS_ZSTD=y)"
+ 	PROC_FW_IGNORE_SYSFS_FALLBACK="0"
+ 	PROC_FW_FORCE_SYSFS_FALLBACK="0"
+ 
+@@ -98,9 +99,14 @@ check_setup()
+ 
+ 	OLD_FWPATH="$(cat /sys/module/firmware_class/parameters/path)"
+ 
+-	if [ "$HAS_FW_LOADER_COMPRESS" = "yes" ]; then
++	if [ "$HAS_FW_LOADER_COMPRESS_XZ" = "yes" ]; then
+ 		if ! which xz 2> /dev/null > /dev/null; then
+-			HAS_FW_LOADER_COMPRESS=""
++			HAS_FW_LOADER_COMPRESS_XZ=""
++		fi
++	fi
++	if [ "$HAS_FW_LOADER_COMPRESS_ZSTD" = "yes" ]; then
++		if ! which zstd 2> /dev/null > /dev/null; then
++			HAS_FW_LOADER_COMPRESS_ZSTD=""
+ 		fi
+ 	fi
+ }
+-- 
+2.36.0.rc1
 
